/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkin.brand;

public class Library {
    public boolean someLibraryMethod() {
      System.out.println("Hello form world");
        return true;

    }
}
