/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkin.brand;

public class Library {
    public boolean someLibraryMethod() {
      System.out.println("Test branch");
      System.out.println("thangtha111111111111111111111ngthang");
        return true;
    }
}
